### ISSUE TITLE
Docs url should be .../dev/ ; not .../latest/

### ISSUE THREAD

**Issue by navidcy** [glwagner/PriceWellerPinkel.jl#118]
<img width="424" alt="Screen Shot 2020-09-22 at 11 23 16 am" src="https://user-images.githubusercontent.com/7112768/93836400-0a044e80-fcc6-11ea-81f4-da6d932b141a.png">

**Comment by glwagner** [comment]
What's the reasoning? I assumed that our recommended way to use the package is to obtain a tagged release from the Julia package manager. Therefore the docs relevant to the tagged release should be advertised.

**Comment by navidcy** [comment]
That's the new default in Documenter unless you change it...

**Comment by glwagner** [comment]
Hmmmmm true. Really only matters for major codes that might have massive breaking changes on `master` / dev. In that case I wouldn't want to send people by default to the dev docs, where'd they could get twisted into knots because the docs don't match the package in their environment. But maybe its better for a small code where versioning is more of a formality to link to dev. It makes sense as a default because sensible versioning should not be assumed I think.

**Comment by navidcy** [comment]
My point is that you should either fix the link the repo's landing page or change 
https://github.com/glwagner/OceanTurb.jl/blob/b0d21cddaaf9aa625146108b5ec96a2a544a2f9f/docs/make.jl#L35
to (I think) this
```julia
    devurl = "latest",
    versions = ["stable" => "v^", "v#.#", devurl => devurl],
```

**Comment by navidcy** [comment]
actually the link works... I'm closing this
