### ISSUE TITLE
memory allocation in KPP

### ISSUE THREAD

**Issue by sandreza** [glwagner/PriceWellerPinkel.jl#20]
When using BenchmarkTools on the iterate function in the KPP example there seems to be a lot of memory allocations
```
@btime iterate!(model, dt, 1000)
yields 
263.532 ms (7311604 allocations: 121.41 MiB)
```
which may be indicate bottleneck for performance.

**Comment by glwagner** [comment]
Hmm yes, we should be able to eliminate memory allocation for the most part. I’ll look into it.

**Comment by glwagner** [comment]
Running

```julia
using Pkg; Pkg.activate("..")

using OceanTurb, Printf, StaticArrays, BenchmarkTools

Ns = (128,)

function atomic_forward_euler_benchmark(m, Δt) 
    @printf "% 24s:" "prepare"
    @btime OceanTurb.update!($m)

    @printf "% 24s:" "calc explicit rhs"
    @btime OceanTurb.calc_explicit_rhs!($(m.timestepper.rhs), $(m.timestepper.eqn), $m) 

    @printf "% 24s:" "update solution"
    @btime OceanTurb.forward_euler_update!($m, $Δt)

    @printf "% 24s:" "tick"
    @btime OceanTurb.tick!($(m.clock), $Δt)
    return nothing
end

@printf "\nAtomic timestepping benchmarking of default configuration...\n"
Δt = 1.1 
for N in Ns

    @printf "N: % 4d, forward Euler\n" N
    m = KPP.Model(N=N, stepper=:ForwardEuler)
    atomic_forward_euler_benchmark(m, Δt) 

    @printf "N: % 4d, backward Euler\n" N
    m = KPP.Model(N=N, stepper=:BackwardEuler)
    atomic_backward_euler_benchmark(m, Δt) 
end
```

From the directory `benchmarks/` on a branch created from commit

https://github.com/glwagner/OceanTurb.jl/commit/6877fdf51baa1bce6999e9f491918e7fe89d4e55

produces, on my Mac:

```julia
Atomic timestepping benchmarking of default configuration...
N:  128, forward Euler
                 prepare:  27.108 μs (1188 allocations: 18.56 KiB)
       calc explicit rhs:  73.233 μs (2564 allocations: 48.13 KiB)
         update solution:  66.033 μs (3588 allocations: 64.13 KiB)
                    tick:  2.599 ns (0 allocations: 0 bytes)
```

Running the [current atomic benchmark]() for KPP produces:

```julia
Atomic timestepping benchmarking of default configuration...
N:  128, forward Euler
                 prepare:  33.732 μs (1195 allocations: 18.67 KiB)
       calc explicit rhs:  48.033 μs (1920 allocations: 30.00 KiB)
         update solution:  914.421 ns (0 allocations: 0 bytes)
                    tick:  2.598 ns (0 allocations: 0 bytes)
```

A single time-step at `N=128` is therefore about 2.01x faster and we allocate 62.7% less memory (which will produce additional speed-ups due to less frequency garbage collection).

Not perfect but a good improvement.

**Comment by ali-ramadhan** [comment]
That's pretty fast. Seems like the way to really speed up the training/optimization would be to parallelize across multiple CPUs which should be pretty easy to do with the Distributed stdlib as it's an "embarrassingly parallel" problem.

A ~50 vCPU instance on Google Cloud costs roughly the same as a V100 GPU instance.

**Comment by glwagner** [comment]
Definitely! This problem doesn't need / isn't good for the GPU.

When we have adaptive time-stepping we need the individual instances to run asynchronously as well.

For optimization of 3D coarse models, we *will* probably want to use the GPU with Oceananigans. I think.

I was actually disappointed that we couldn't eliminate memory allocation entirely. It seems the compiler thinks a bit of allocation is better than the no-allocation I was going for. 

I'm not sure I completely understand the timings... probably there is a memory-boundedness-phenomenon occurring, which is why update solution and calc rhs are so different (even though both involve one loop per solution field). It's also wild that `prepare` is such a significant fraction of the computation.

**Comment by ali-ramadhan** [comment]
There seem to be a suspiciously high number of allocations, seems like something is being allocated element-wise...

Just skimming through your code I saw a few functions that are called super frequently but aren't inlined. Not sure if function calls allocate memory? I wonder if inlining them will reduce the number of allocations?

For `prepare` maybe inline this:
https://github.com/glwagner/OceanTurb.jl/blob/05a4f9e09464e1ca0e1196bb2fc0502618ec2f27/src/boundary_conditions.jl#L11

For `calc_explicit_rhs` maybe inline these:
https://github.com/glwagner/OceanTurb.jl/blob/05a4f9e09464e1ca0e1196bb2fc0502618ec2f27/src/fields.jl#L285-L300

**Comment by glwagner** [comment]
Decorating those with `@inline` during my personal 'performance hackathon' yesterday had no effect on the benchmarks. Using the annotation `@propagate_inbounds` occasionally affected performance *negatively* and produced more memory allocation. I have no idea why. I don't understand when to inline and when not to. There is also an annotation `@noinline` which is also supposed to help performance in some cases... ?

Perhaps something to revisit in a few weeks, maybe when my brain has reset.

**Comment by glwagner** [comment]
It's does seem to me that performance optimization on small yet complex problems like this one is a bit tricky.

**Comment by ali-ramadhan** [comment]
Ah interesting. Yeah maybe this is where some detailed profiling would be most helpful.

It seems that aggressive inlining is the way to go on a GPU, I guess things are less clear on a CPU.
